[project]
name = "pyigr"
version = "2026.9.177"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [    
    'networkx'  # v3 has no deps
]
[project.optional-dependencies]
state = []
dask = ['dask']
reaktiv = ['reactive']
# exec-daskdist = ['dask[distributed]'] can probbly be handled by user

[dependency-groups]
dev = [
    'icecream',
    'fire',
    "marimo", "pyzmq",'ipdb',
    # examples
    'python-box', 'wrapt', 
]


[build-system]
requires = ["uv_build"]
build-backend = "uv_build"
